name: ink_abi
description: ink! abi encoder and decoder
version: 0.3.1
homepage: https://github.com/leonardocustodio/polkadart/tree/main/packages/ink_abi
repository: https://github.com/leonardocustodio/polkadart
resolution: workspace

environment:
  sdk: ^3.6.0

dependencies:
  json_schema: ^5.2.1
  polkadart:
    git:
      url: https://github.com/Quantus-Network/polkadart.git
      ref: 0_7_3_quantus_2
      path: packages/polkadart
  polkadart_scale_codec:
    git:
      url: https://github.com/Quantus-Network/polkadart.git
      ref: 0_7_3_quantus_2
      path: packages/polkadart_scale_codec
  substrate_metadata:
    git:
      url: https://github.com/Quantus-Network/polkadart.git
      ref: 0_7_3_quantus_2
      path: packages/substrate_metadata
  utility: ^1.0.3

dev_dependencies:
  lints: ^6.0.0
  test: ^1.26.3
